name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          user: JakeyGilly
          optimize: svg
          experimental_features: --optimize-svg
          output_action: pull-request-merge
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, organization_member, collaborator
  repo-1:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          filename: repo-1.svg
          repo: CompactifierPlusPlus
          optimize: svg
          experimental_features: --optimize-svg
          output_action: pull-request-merge
          plugin_introduction: yes
  repo-2:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          filename: repo-2.svg
          repo: instant-messenger
          optimize: svg
          experimental_features: --optimize-svg
          output_action: pull-request-merge
          plugin_introduction: yes
          
