name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  personal-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          user: JakeyGilly
          optimize: svg
          experimental_features: --optimize-svg
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, organization_member, collaborator
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
  org-1-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          filename: org-1.svg
          user: FinderDiscord
          optimize: svg
          experimental_features: --optimize-svg
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, organization_member, collaborator
  org-2-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          filename: org-2.svg
          user: JohnCubeGames
          optimize: svg
          experimental_features: --optimize-svg
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, organization_member, collaborator
  repo:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          filename: repo.svg
          template: repository
          base: header
          optimize: svg
          experimental_features: --optimize-svg
          plugin_repositories: yes
          plugin_repositories_featured: JakeyGilly/CompactifierPlusPlus, JakeyGilly/instant-messenger, FinderDiscord/Finder, Explorer017/GMTK-GameJam-Entry-2021
          
